-- NOTE: Run manually in the Supabase Dashboard SQL editor, AFTER
-- 0011_jobs_module.sql. Seed content only — safe to re-run is NOT
-- guaranteed (no ON CONFLICT DO NOTHING), so only run this once against
-- a given project. All companies below are fictional.

insert into public.jobs (
  slug, title, company, role_slug, location, work_mode, job_type,
  experience_level, experience_min_years, experience_max_years,
  salary_min, salary_max, skills, description, responsibilities,
  eligibility, apply_url
) values

('software-engineer-technova-fresher', 'Software Engineer', 'TechNova Solutions', 'software-engineer', 'Bengaluru, India', 'hybrid', 'full-time',
 'fresher', 0, 1, 4, 6,
 ARRAY['JavaScript', 'React', 'Node.js', 'Git'],
 'Join our product engineering team building customer-facing web applications used by thousands of businesses daily.',
 ARRAY['Build and maintain features across the stack', 'Write clean, tested code', 'Participate in code reviews'],
 ARRAY['B.Tech/B.E. in Computer Science or related field', 'Strong fundamentals in data structures and algorithms'],
 'https://example.com/careers/technova/software-engineer'),

('software-engineer-skylark-remote', 'Software Engineer II', 'Skylark Systems', 'software-engineer', 'Remote', 'remote', 'full-time',
 '1-3-years', 1, 3, 8, 12,
 ARRAY['TypeScript', 'Next.js', 'PostgreSQL', 'AWS'],
 'Own end-to-end delivery of features for our SaaS platform, working closely with product and design.',
 ARRAY['Design and implement scalable backend services', 'Mentor junior engineers', 'Improve deployment pipelines'],
 ARRAY['1-3 years of professional software development experience', 'Comfortable working async in a remote team'],
 null),

('qa-engineer-brightpath-fresher', 'QA Engineer', 'Brightpath Analytics', 'qa-engineer', 'Pune, India', 'onsite', 'full-time',
 'fresher', 0, 1, 3, 5,
 ARRAY['Manual Testing', 'Test Case Design', 'SQL', 'Jira'],
 'Ensure the quality of our analytics dashboard products through rigorous manual and exploratory testing.',
 ARRAY['Write and execute test cases', 'Log and track defects', 'Collaborate with developers on fixes'],
 ARRAY['B.Tech/B.E. or equivalent', 'Strong attention to detail'],
 'https://example.com/careers/brightpath/qa-engineer'),

('qa-engineer-nimbus-contract', 'Senior QA Automation Engineer', 'Nimbus Cloud Labs', 'qa-engineer', 'Remote', 'remote', 'contract',
 '3-5-years', 3, 5, 10, 14,
 ARRAY['Selenium', 'Playwright', 'CI/CD', 'JavaScript'],
 'Build and maintain our automated test suite covering web and API layers for a fast-moving cloud product.',
 ARRAY['Design automation frameworks', 'Integrate tests into CI/CD', 'Triage flaky tests'],
 ARRAY['3-5 years in QA automation', 'Experience with Playwright or Selenium'],
 null),

('frontend-developer-pixelforge-hybrid', 'Frontend Developer', 'Pixelforge Studio', 'frontend-developer', 'Hyderabad, India', 'hybrid', 'full-time',
 '1-3-years', 1, 3, 6, 9,
 ARRAY['React', 'Tailwind CSS', 'TypeScript', 'Figma'],
 'Craft pixel-perfect, accessible interfaces for our design-led product studio''s client projects.',
 ARRAY['Translate Figma designs into responsive UI', 'Optimise for performance and accessibility', 'Collaborate closely with designers'],
 ARRAY['1-3 years building production React applications', 'A strong eye for design detail'],
 'https://example.com/careers/pixelforge/frontend-developer'),

('frontend-developer-vertex-remote', 'Frontend Developer (Fresher)', 'Vertex Digital', 'frontend-developer', 'Remote', 'remote', 'full-time',
 'fresher', 0, 1, 4, 6,
 ARRAY['HTML', 'CSS', 'JavaScript', 'React'],
 'Start your frontend career building marketing sites and web apps for our growing roster of clients.',
 ARRAY['Build responsive pages from design mockups', 'Fix cross-browser issues', 'Learn our component library'],
 ARRAY['Solid HTML/CSS/JS fundamentals', 'A portfolio of personal or academic projects'],
 null),

('backend-developer-corestack-onsite', 'Backend Developer', 'Corestack Technologies', 'backend-developer', 'Bengaluru, India', 'onsite', 'full-time',
 '3-5-years', 3, 5, 14, 20,
 ARRAY['Node.js', 'PostgreSQL', 'Redis', 'Docker'],
 'Design and scale the backend services powering our fintech platform''s transaction processing.',
 ARRAY['Design database schemas and APIs', 'Ensure system reliability and observability', 'Review pull requests'],
 ARRAY['3-5 years backend engineering experience', 'Experience with distributed systems'],
 'https://example.com/careers/corestack/backend-developer'),

('backend-developer-dataforge-hybrid', 'Backend Developer', 'DataForge Inc', 'backend-developer', 'Chennai, India', 'hybrid', 'full-time',
 '1-3-years', 1, 3, 8, 12,
 ARRAY['Python', 'Django', 'PostgreSQL', 'REST APIs'],
 'Build robust APIs and services for our data-processing pipeline used across multiple products.',
 ARRAY['Develop and maintain REST APIs', 'Write unit and integration tests', 'Optimise query performance'],
 ARRAY['1-3 years with Python web frameworks', 'Understanding of relational databases'],
 null),

('data-analyst-insight-onsite', 'Data Analyst', 'Insight Metrics', 'data-analyst', 'Gurugram, India', 'onsite', 'full-time',
 'fresher', 0, 1, 4, 6,
 ARRAY['SQL', 'Excel', 'Power BI', 'Statistics'],
 'Turn raw business data into clear insights that shape decisions across our client portfolio.',
 ARRAY['Build dashboards and reports', 'Clean and validate datasets', 'Present findings to stakeholders'],
 ARRAY['Degree in Statistics, Economics, or related field', 'Comfortable with SQL and spreadsheets'],
 'https://example.com/careers/insight-metrics/data-analyst'),

('data-analyst-quantify-remote', 'Data Analyst', 'Quantify Labs', 'data-analyst', 'Remote', 'remote', 'full-time',
 '1-3-years', 1, 3, 7, 10,
 ARRAY['SQL', 'Python', 'Tableau', 'A/B Testing'],
 'Partner with product teams to analyse experiments and user behaviour across our consumer app.',
 ARRAY['Design and analyse A/B tests', 'Build self-serve dashboards', 'Communicate insights to non-technical teams'],
 ARRAY['1-3 years in an analytics role', 'Proficiency in SQL and a BI tool'],
 null),

('ai-engineer-neuralarc-hybrid', 'AI Engineer', 'NeuralArc AI', 'ai-engineer', 'Bengaluru, India', 'hybrid', 'full-time',
 '3-5-years', 3, 5, 18, 25,
 ARRAY['Python', 'PyTorch', 'NLP', 'MLOps'],
 'Build and deploy machine learning models powering our natural language products at scale.',
 ARRAY['Train and evaluate ML models', 'Build model deployment pipelines', 'Collaborate with product on ML features'],
 ARRAY['3-5 years in applied ML/AI', 'Experience shipping models to production'],
 'https://example.com/careers/neuralarc/ai-engineer'),

('ai-engineer-cognitive-intern', 'AI Engineering Intern', 'Cognitive Systems', 'ai-engineer', 'Remote', 'remote', 'internship',
 'fresher', 0, 1, 2, 3,
 ARRAY['Python', 'Machine Learning', 'NumPy', 'Pandas'],
 'Support our ML team with data preparation, experimentation, and model evaluation.',
 ARRAY['Prepare and clean training datasets', 'Run model experiments', 'Document findings'],
 ARRAY['Currently pursuing or recently completed a degree in CS/ML', 'Familiarity with Python data tooling'],
 null),

('devops-engineer-cloudbridge-hybrid', 'DevOps Engineer', 'CloudBridge Technologies', 'devops-engineer', 'Pune, India', 'hybrid', 'full-time',
 '1-3-years', 1, 3, 10, 14,
 ARRAY['AWS', 'Terraform', 'Kubernetes', 'CI/CD'],
 'Own the infrastructure and deployment pipelines for our multi-tenant cloud platform.',
 ARRAY['Manage cloud infrastructure as code', 'Improve CI/CD pipelines', 'Monitor system health and incidents'],
 ARRAY['1-3 years in DevOps or SRE roles', 'Hands-on experience with AWS and Terraform'],
 'https://example.com/careers/cloudbridge/devops-engineer'),

('devops-engineer-infranet-senior', 'Senior DevOps Engineer', 'Infranet Solutions', 'devops-engineer', 'Remote', 'remote', 'full-time',
 '5-plus-years', 5, 12, 22, 30,
 ARRAY['Kubernetes', 'AWS', 'Terraform', 'Observability'],
 'Lead infrastructure strategy and reliability engineering for a platform serving millions of requests daily.',
 ARRAY['Define infrastructure architecture', 'Lead incident response', 'Mentor the platform team'],
 ARRAY['5+ years in infrastructure/platform engineering', 'Track record owning production reliability'],
 null),

('ui-ux-designer-studiocanvas-onsite', 'UI/UX Designer', 'Studio Canvas', 'ui-ux-designer', 'Mumbai, India', 'onsite', 'full-time',
 'fresher', 0, 1, 4, 6,
 ARRAY['Figma', 'User Research', 'Prototyping', 'Design Systems'],
 'Design intuitive, beautiful experiences for our clients'' web and mobile products.',
 ARRAY['Create wireframes and high-fidelity mockups', 'Conduct usability sessions', 'Maintain the design system'],
 ARRAY['Degree in Design or equivalent portfolio', 'Proficiency in Figma'],
 'https://example.com/careers/studio-canvas/ui-ux-designer'),

('ui-ux-designer-formify-parttime', 'Product Designer (Part-Time)', 'Formify Design Co', 'ui-ux-designer', 'Remote', 'remote', 'part-time',
 '1-3-years', 1, 3, 6, 9,
 ARRAY['Figma', 'Interaction Design', 'User Testing'],
 'Shape the design direction of our productivity app alongside a small, senior team.',
 ARRAY['Own design for a core product area', 'Run lightweight user testing', 'Iterate based on feedback'],
 ARRAY['1-3 years of product design experience', 'A strong portfolio of shipped work'],
 null),

('product-manager-northstar-hybrid', 'Product Manager', 'Northstar Products', 'product-manager', 'Bengaluru, India', 'hybrid', 'full-time',
 '3-5-years', 3, 5, 20, 28,
 ARRAY['Product Strategy', 'Roadmapping', 'Analytics', 'Stakeholder Management'],
 'Own the roadmap for a core product line, working closely with engineering, design, and sales.',
 ARRAY['Define product strategy and roadmap', 'Write specs and prioritise backlog', 'Analyse product metrics'],
 ARRAY['3-5 years in product management', 'Experience shipping B2B or B2C products'],
 'https://example.com/careers/northstar/product-manager'),

('product-manager-launchpad-senior', 'Senior Product Manager', 'Launchpad Ventures', 'product-manager', 'Remote', 'remote', 'full-time',
 '5-plus-years', 5, 15, 30, 40,
 ARRAY['Product Vision', 'Growth Strategy', 'Cross-functional Leadership'],
 'Lead product strategy across our portfolio of consumer products, reporting directly to the VP of Product.',
 ARRAY['Set product vision across multiple squads', 'Lead cross-functional planning', 'Represent product to leadership'],
 ARRAY['5+ years in product management, ideally with team leadership experience', 'A track record of shipping impactful products'],
 null);
