import { Sparkles } from "lucide-react";
import Tooltip from "@/components/ui/Tooltip";

/**
 * Every AI-generated result any feature shows must carry this — the
 * one shared disclosure primitive Phase 0 asks for, so no feature
 * invents its own wording or forgets it entirely. Addresses the PRD's
 * own flagged risk ("hallucinated content presented as fact") at the
 * UI layer: content is always visibly labeled as AI-generated.
 */
export default function AIDisclosureBadge({ className = "" }: { className?: string }) {
  return (
    <Tooltip content="This content was generated by AI and may contain mistakes. Always verify before relying on it.">
      <span
        className={`inline-flex w-fit items-center gap-1.5 rounded-full bg-amber-dim/10 px-3 py-1 text-xs font-bold text-amber-dim ${className}`}
      >
        <Sparkles size={12} />
        AI-generated
      </span>
    </Tooltip>
  );
}
